export const MATCHES_ERROR = 'MATCHES_ERROR';
export const MATCHES_LOADING = 'MATCHES_LOADING';
export const MATCHES_FETCH_SUCCESS = 'MATCHES_FETCH_SUCCESS';

export const REC_ERROR = 'RECOMMENDATIONS_ERROR';
export const REC_LOADING = 'RECOMMENDATIONS_LOADING';
export const REC_FETCH_SUCCESS = 'RECOMMENDATIONS_FETCH_SUCCESS';
export const REC_POP = 'RECOMMENDATIONS_POP';
export const REC_SUBMIT_SUCCESS = 'RECOMMENDATIONS_SUBMIT_SUCCESS';

export const PROFILE_LOADING = 'PROFILE__LOADING';
export const PROFILE_FETCHED = 'PROFILE__FETCHED_DATA';
export const PROFILE_ERROR = 'PROFILE__ERRORED';

export const SHOW_PROFILE = 'PROFILE__SHOW';
export const HIDE_PROFILE = 'PROFILE__HIDE';
