export const MATCHES_ERROR = 'MATCHES_ERROR';
export const MATCHES_LOADING = 'MATCHES_LOADING';
export const MATCHES_FETCH_SUCCESS = 'MATCHES_FETCH_SUCCESS';
export const ONE_MATCH_FETCH_SUCCESS = 'ONE_MATCH_FETCH_SUCCESS';
export const CLEAR_ONE_MATCH = 'CLEAR_ONE_MATCH';

export const REC_ERROR = 'RECOMMENDATIONS_ERROR';
export const REC_LOADING = 'RECOMMENDATIONS_LOADING';
export const REC_FETCH_SUCCESS = 'RECOMMENDATIONS_FETCH_SUCCESS';
export const REC_POP = 'RECOMMENDATIONS_POP';
export const REC_SUBMIT_SUCCESS = 'RECOMMENDATIONS_SUBMIT_SUCCESS';

export const USER_INFO_LOADING = 'USER_INFO_LOADING';
export const USER_INFO_FETCH_SUCCESS = 'USER_INFO_FETCH_SUCCESS';
export const USER_INFO_SAVE_SUCCESS = 'USER_INFO_SAVE_SUCCESS';
export const USER_INFO_ERROR = 'USER_INFO_ERRORED';

export const FILTERS_LOADING = 'FILTERS_LOADING';
export const FILTERS_FETCH_SUCCESS = 'FILTERS_FETCH_SUCCESS';
export const FILTERS_ERROR = 'FILTERS_ERRORED';

export const SHOW_PROFILE = 'SHOW_PROIFLE';
export const HIDE_PROFILE = 'HIDE_PROFILE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
