export const MATCHES_ERROR = 'MATCHES_ERROR';
export const MATCHES_LOADING = 'MATCHES_LOADING';
export const MATCHES_FETCH_SUCCESS = 'MATCHES_FETCH_SUCCESS';
export const MATCHES_MATCHED = 'MATCHES_USERS_MATCHED';
export const MATCHES_REDIRECTED = 'MATCHEDS_USERS_MATCHED_REDIRECTED';

export const REC_ERROR = 'RECOMMENDATIONS_ERROR';
export const REC_LOADING = 'RECOMMENDATIONS_LOADING';
export const REC_FETCH_SUCCESS = 'RECOMMENDATIONS_FETCH_SUCCESS';
export const REC_SUBMIT_SUCCESS = 'RECOMMENDATIONS_SUBMIT_SUCCESS';

export const REF_ERROR = 'REF__ERRORED';
export const REF_LOADING = 'REF__LOADING';
export const REF_FETCHED = 'REF__FETCHED';
