-- THIS WILL GET RID OF ALL THE TABLES
DROP TABLE IF EXISTS UserMatches;
DROP TABLE IF EXISTS Matches;
DROP TABLE IF EXISTS UserStudy;
DROP TABLE IF EXISTS UserPreference;
DROP TABLE IF EXISTS UserInterests;
DROP TABLE IF EXISTS Likes;
DROP TABLE IF EXISTS UserPicture;
DROP TABLE IF EXISTS UsersInfo;
DROP TABLE IF EXISTS InterestsType;
DROP TABLE IF EXISTS ReligionType;
DROP TABLE IF EXISTS StudyType;
DROP TABLE IF EXISTS EducationType;
DROP TABLE IF EXISTS GenderType;
DROP TABLE IF EXISTS Users;